// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login.sql

package database

import (
	"context"
	"database/sql"
)

const login = `-- name: Login :one
select id, created_at, updated_at, email, hashed_password
from users
where email = $1 and hashed_password = $2
`

type LoginParams struct {
	Email          sql.NullString
	HashedPassword string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, login, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
