#!/usr/bin/env bash

# Need at least one argument
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 [args-for-program...] <website-link>"
  exit 1
fi

# Save all arguments in an array
args=("$@")

# Extract last argument (the URL)
url="${args[-1]}"

# Remove last argument from array
unset 'args[-1]'

# Parse last path component as before
last_component="${url%/}"
last_component="${last_component##*/}"

if [ "$#" -ne 1 ]; then
    bootdev "${args[@]}" "$last_component"
else
    bootdev submit "$last_component"
fi
